import { Router, type IRouter } from "express";
import healthRouter from "./health";
import agentsRouter from "./agents";
import channelsRouter from "./channels";
import tasksRouter from "./tasks";
import telemetryRouter from "./telemetry";
import swarmRouter from "./swarm";
import commandsRouter from "./commands";
import steelRouter from "./steel";
import aiRouter from "./ai";
import externalRouter from "./external";
import integrationsRouter from "./integrations";
import selfCheckRouter from "./selfCheck";
import authRouter from "./auth";
import vaultRouter from "./vault";
import socialRouter from "./social";
import uploadsRouter from "./uploads";
import worldRouter from "./world";
import discordRouter from "./discord";
import n8nRouter from "./n8n";
import mvpGovernorRouter from "./mvpGovernor";
import settingsRouter from "./settings";
import hermesRouter from "./hermes";
import openhandsRouter from "./openhands";
import crawl4aiRouter from "./crawl4ai";
import mem0Router from "./mem0";
import doclingRouter from "./docling";
import knowledgeRouter from "./knowledge";
import { devicesRouter } from "@workspace/remote-control/routes";
import { missionsRouter } from "./missions";
import referenceRouter from "./reference";
import { requireOperator } from "../lib/auth";

const router: IRouter = Router();

router.use(healthRouter);
router.use("/agents", agentsRouter);
router.use("/channels", channelsRouter);
router.use("/tasks", tasksRouter);
router.use(telemetryRouter);
router.use("/swarm", swarmRouter);
router.use(commandsRouter);
router.use(steelRouter);
router.use(aiRouter);
router.use("/discord", discordRouter);
router.use(n8nRouter);
router.use(mvpGovernorRouter);
router.use(settingsRouter);
router.use(uploadsRouter);
router.use(worldRouter);
router.use(externalRouter);
router.use(integrationsRouter);
router.use(selfCheckRouter);
router.use(authRouter);
router.use("/hermes", hermesRouter);
router.use("/openhands", openhandsRouter);
router.use("/crawl4ai", crawl4aiRouter);
router.use("/mem0", mem0Router);
router.use("/docling", doclingRouter);
router.use("/knowledge", knowledgeRouter);
router.use("/devices", devicesRouter);
router.use("/missions", missionsRouter);
router.use(referenceRouter);
router.use(requireOperator, vaultRouter);
router.use(requireOperator, socialRouter);

export default router;
